version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance
    env_file:
      - ./backend/.env

  frontend:
    build: ./FRONTEND/webapp
    container_name: frontend
    ports:
      - "3000:3000"
    command: npm run dev   # mode dev pour hot reload
    develop:
      watch:
        - action: sync
          path: ./FRONTEND/webapp
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./FRONTEND/webapp/package.json
    depends_on:
      - backend
