"""Initial migration

Revision ID: a66f1674deb1
Revises: 
Create Date: 2025-11-23 20:59:20.049574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66f1674deb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('certifications',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validity_years', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('matricule', sa.String(length=10), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name', 'hire_date', name='uq_employee_name_hiredate'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('fournisseurs',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('marques',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('processes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=55), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unites',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=True),
    sa.Column('type_unite', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('articles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('type_article', sa.String(length=20), nullable=True),
    sa.Column('id_categorie', sa.String(length=36), nullable=True),
    sa.Column('id_unite', sa.String(length=36), nullable=True),
    sa.Column('id_marque', sa.String(length=36), nullable=True),
    sa.Column('id_fournisseur', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categorie'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['id_fournisseur'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['id_marque'], ['marques.id'], ),
    sa.ForeignKeyConstraint(['id_unite'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('divisions',
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'type', 'name', name='uq_division_site')
    )
    op.create_table('employee_certifications',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('certification_id', sa.String(length=36), nullable=False),
    sa.Column('obtained_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_steps',
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_compositions',
    sa.Column('article_parent_id', sa.String(length=36), nullable=False),
    sa.Column('article_enfant_id', sa.String(length=36), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unite_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_enfant_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['article_parent_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['unite_id'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caracteristiques_articles',
    sa.Column('id_article', sa.String(length=36), nullable=False),
    sa.Column('pcb', sa.Integer(), nullable=True),
    sa.Column('ean', sa.String(length=20), nullable=True),
    sa.Column('DLC', sa.Integer(), nullable=True),
    sa.Column('DGR', sa.Integer(), nullable=True),
    sa.Column('conditionnement_a_chaud', sa.Boolean(), nullable=True),
    sa.Column('etiquette_sur_chaque_colis', sa.Boolean(), nullable=True),
    sa.Column('gamme', sa.String(length=100), nullable=True),
    sa.Column('id_unite', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['id_unite'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_article')
    )
    op.create_table('division_employees',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'division_id', 'start_date', name='uq_employee_division')
    )
    op.create_table('machines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=False),
    sa.Column('parent_machine_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['parent_machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('palettisations',
    sa.Column('id_article', sa.String(length=36), nullable=False),
    sa.Column('nb_colis_par_couche', sa.Integer(), nullable=True),
    sa.Column('nb_couches_par_palette', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_article', 'id')
    )
    op.create_table('production_recipes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('recipe_type', sa.String(length=20), nullable=True),
    sa.Column('article_output_id', sa.String(length=36), nullable=False),
    sa.Column('taille_lot_ref', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_output_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stocks',
    sa.Column('id_article', sa.String(length=36), nullable=False),
    sa.Column('id_unite', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('dlc', sa.Date(), nullable=True),
    sa.Column('numero_lot', sa.String(length=100), nullable=True),
    sa.Column('is_bloque', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_unite'], ['unites.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('idx_stock_article', ['id_article'], unique=False)
        batch_op.create_index('idx_stock_lot', ['numero_lot'], unique=False)

    op.create_table('machine_documents',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvements_stock',
    sa.Column('id_stock', sa.String(length=36), nullable=False),
    sa.Column('type_mouvement', sa.Enum('ENTREE', 'SORTIE', 'AJUSTEMENT', 'MOUVEMENT', name='typemouvement'), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('date_mouvement', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('utilisateur', sa.String(length=100), nullable=True),
    sa.Column('id_unite', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_unite'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_machines',
    sa.Column('process_step_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['process_step_id'], ['process_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_orders',
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('unite_article_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('quantity_planned', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quantity_rejected', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('product_DLC', sa.Date(), nullable=True),
    sa.Column('product_DGR', sa.Date(), nullable=True),
    sa.Column('fabrication_start_date_planned', sa.Date(), nullable=False),
    sa.Column('fabrication_start_date_real', sa.DateTime(), nullable=True),
    sa.Column('fabrication_end_date_real', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ligne_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['ligne_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['production_recipes.id'], ),
    sa.ForeignKeyConstraint(['unite_article_id'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_orders_batch_number'), ['batch_number'], unique=False)

    op.create_table('recette_ingredients',
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('unite_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_proportional', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['production_recipes.id'], ),
    sa.ForeignKeyConstraint(['unite_id'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_target_specs',
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('spec_name', sa.String(length=100), nullable=False),
    sa.Column('spec_unit_id', sa.String(length=36), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('target_min', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['production_recipes.id'], ),
    sa.ForeignKeyConstraint(['spec_unit_id'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_materials',
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=False),
    sa.Column('consumed_quantity', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_outputs',
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_tasks',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('process_step_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['process_step_id'], ['process_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_tasks')
    op.drop_table('production_outputs')
    op.drop_table('production_materials')
    op.drop_table('recipe_target_specs')
    op.drop_table('recette_ingredients')
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_orders_batch_number'))

    op.drop_table('production_orders')
    op.drop_table('process_machines')
    op.drop_table('mouvements_stock')
    op.drop_table('machine_documents')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_lot')
        batch_op.drop_index('idx_stock_article')

    op.drop_table('stocks')
    op.drop_table('production_recipes')
    op.drop_table('palettisations')
    op.drop_table('machines')
    op.drop_table('division_employees')
    op.drop_table('caracteristiques_articles')
    op.drop_table('article_compositions')
    op.drop_table('process_steps')
    op.drop_table('employee_certifications')
    op.drop_table('divisions')
    op.drop_table('articles')
    op.drop_table('unites')
    op.drop_table('sites')
    op.drop_table('processes')
    op.drop_table('marques')
    op.drop_table('fournisseurs')
    op.drop_table('employees')
    op.drop_table('certifications')
    op.drop_table('categories')
    # ### end Alembic commands ###
